default_host = "localhost:3000"

[[module]]
# Example executing a Web Assembly Text file
route = "/"
module = "examples/hello.wat"

[[module]]
# Example running a WASM file.
route = "/hello/..."
module = "examples/hello.wasm"

[[module]]
route = "/http-example"
module = "examples/http-example.wasm"
allowed_hosts = ["https://api.brigade.sh"]
http_max_concurrency = 2

[[module]]
# Example error.
route = "/error"
module = "examples/error.wat"

[[module]]
# Example logging.
route = "/log"
module = "examples/log.wasm"
